import User from '../models/User.js';
import Book from '../models/Book.js';
import Loan from '../models/Loan.js';
import StockItem from '../models/StockItem.js';
import Admission from '../models/Admission.js';
import News from '../models/News.js';
import AuditLog from '../models/AuditLog.js';
import { ok } from '../utils/api.js';

export async function adminDashboard(_req, res) { const [totalUsers, activeUsers, totalBooks, activeLoans, overdueLoans, totalStockItems, lowStockItems, outOfStockItems, totalApplications, recentActivity, publishedNews] = await Promise.all([User.countDocuments(), User.countDocuments({ status: 'active' }), Book.countDocuments({ active: true }), Loan.countDocuments({ returnDate: null }), Loan.countDocuments({ returnDate: null, dueDate: { $lt: new Date() } }), StockItem.countDocuments({ active: true }), StockItem.countDocuments({ active: true, $expr: { $and: [{ $gt: ['$quantity', 0] }, { $lte: ['$quantity', '$minLevel'] }] } }), StockItem.countDocuments({ active: true, quantity: { $lte: 0 } }), Admission.countDocuments(), AuditLog.find().sort('-createdAt').limit(10), News.countDocuments({ published: true })]); return ok(res, { totalUsers, activeUsers, totalBooks, activeLoans, overdueLoans, totalStockItems, lowStockItems, outOfStockItems, totalApplications, recentActivity, websiteContentStatistics: { publishedNews } }); }
export async function managementDashboard(_req, res) { const [applications, books, loans, stock, activity] = await Promise.all([Admission.aggregate([{ $group: { _id: '$status', count: { $sum: 1 } } }]), Book.aggregate([{ $match: { active: true } }, { $group: { _id: null, totalBooks: { $sum: 1 }, totalCopies: { $sum: '$totalCopies' }, borrowedCopies: { $sum: '$borrowedCopies' } } }]), Loan.countDocuments({ returnDate: null }), StockItem.find({ active: true }), AuditLog.find().sort('-createdAt').limit(10)]); return ok(res, { applications, books: books[0] || { totalBooks: 0, totalCopies: 0, borrowedCopies: 0 }, borrowedBooks: loans, overdueBooks: await Loan.countDocuments({ returnDate: null, dueDate: { $lt: new Date() } }), totalStockItems: stock.length, lowStockItems: stock.filter((i) => i.quantity > 0 && i.quantity <= i.minLevel).length, outOfStockItems: stock.filter((i) => i.quantity <= 0).length, stockValue: stock.reduce((sum, i) => sum + i.quantity * i.unitPrice, 0), recentActivity: activity }); }
export async function librarySummary(_req, res) { const [summary, overdue, returned] = await Promise.all([Book.aggregate([{ $match: { active: true } }, { $group: { _id: null, totalBooks: { $sum: 1 }, totalCopies: { $sum: '$totalCopies' }, borrowedCopies: { $sum: '$borrowedCopies' } } }]), Loan.countDocuments({ returnDate: null, dueDate: { $lt: new Date() } }), Loan.countDocuments({ status: 'returned' })]); const data = summary[0] || { totalBooks: 0, totalCopies: 0, borrowedCopies: 0 }; return ok(res, { ...data, availableCopies: data.totalCopies - data.borrowedCopies, overdueLoans: overdue, returnedLoans: returned }); }
