import fs from 'fs';
import crypto from 'crypto';
import path from 'path';
import { fileURLToPath } from 'url';
import bcrypt from 'bcryptjs';
import { connectDatabase } from '../config/database.js';
import { UPLOADS_ROOT } from '../config/localStorage.js';
import { env } from '../config/env.js';
import User from '../models/User.js';
import Book from '../models/Book.js';
import StockItem from '../models/StockItem.js';
import Supplier from '../models/Supplier.js';
import Program from '../models/Program.js';
import Department from '../models/Department.js';
import Staff from '../models/Staff.js';
import News from '../models/News.js';
import Gallery from '../models/Gallery.js';
import WebsiteSetting from '../models/WebsiteSetting.js';
import Role from '../models/Role.js';
import Permission from '../models/Permission.js';
import AuditLog from '../models/AuditLog.js';
import Notification from '../models/Notification.js';
import Loan from '../models/Loan.js';
import StockTransaction from '../models/StockTransaction.js';
import DamagedStock from '../models/DamagedStock.js';
import DisposedStock from '../models/DisposedStock.js';
import Report from '../models/Report.js';
import SystemSetting from '../models/SystemSetting.js';
import Equipment from '../models/Equipment.js';
import EquipmentRetirementRequest from '../models/EquipmentRetirementRequest.js';
import EquipmentArchiveRequest from '../models/EquipmentArchiveRequest.js';
import Event from '../models/Event.js';
import Admission from '../models/Admission.js';
import ContactMessage from '../models/ContactMessage.js';
import StockReconciliation from '../models/StockReconciliation.js';
import StockArchiveRequest from '../models/StockArchiveRequest.js';
import { seedDemoData } from './demoData.js';
import { SEED_BOOKS } from '../../../src/data/library.js';
import { SEED_ITEMS, SEED_SUPPLIERS } from '../../../src/data/stock.js';
import { PROGRAMS, DEPARTMENTS, STAFF, NEWS, GALLERY } from '../../../src/data/content.js';

// Demo images: on-brand SVGs generated by generate-assets.js, copied from
// the versioned src/seed/assets/ folder into the local uploads/ directory
// (the same place real admin-uploaded images land) so News, Staff, Gallery,
// Books, and the website branding all have working local images out of the box.
// Seeding DELETES existing users and content. Never let it run on a live database by accident.
if (env.nodeEnv === 'production' && process.env.SEED_CONFIRM_WIPE !== 'yes') {
  console.error('Refusing to seed in production: this deletes all existing data. Set SEED_CONFIRM_WIPE=yes if you really want that.');
  process.exit(1);
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SEED_ASSETS_SRC = path.join(__dirname, 'assets');
const SEED_ASSETS_DEST = path.join(UPLOADS_ROOT, 'seed');
fs.rmSync(SEED_ASSETS_DEST, { recursive: true, force: true });
fs.cpSync(SEED_ASSETS_SRC, SEED_ASSETS_DEST, { recursive: true });
// Stored WITHOUT the server address, so the images keep working after the site moves to a real domain.
const seedImage = (relPath) => ({ imageUrl: `/uploads/seed/${relPath}`, publicId: `seed/${relPath}` });

const demoUsers = [
  ['Jean de Dieu Habimana', 'admin', 'ninzizaaime31@gmail.com', 'Admin@123', 'admin'],
  ['Marie Claire Uwase', 'librarian', 'librarian@ramburagarcons.rw', 'Library@123', 'librarian'],
  ['Emmanuel Nshuti', 'stock', 'stock@ramburagarcons.rw', 'Stock@123', 'stock_manager'],
  ['Fiston Mukiza', 'equipment', 'equipment@ramburagarcons.rw', 'Equipment@123', 'equipment_manager'],
  ['Bro. Alphonse Ntawuruhunga', 'director', 'director@ramburagarcons.rw', 'Director@123', 'management'],
];
// Demo passwords are for local development only. In production every account gets a random password
// that is printed once at the end of the seed.
const isProduction = env.nodeEnv === 'production';
const users = demoUsers.map(([fullName, username, email, demoPassword, role]) => [
  fullName, username, email, isProduction ? `${crypto.randomBytes(9).toString('base64url')}#7a` : demoPassword, role,
]);

await connectDatabase();
await User.deleteMany({});
await User.insertMany(await Promise.all(users.map(async ([fullName, username, email, password, role]) => ({
  fullName, username, email, role, passwordHash: await bcrypt.hash(password, 12), status: 'active', lastActivity: new Date(),
}))));
await Promise.all([
  Book.deleteMany({}),
  StockItem.deleteMany({}),
  Supplier.deleteMany({}),
  StockTransaction.deleteMany({}),
  DamagedStock.deleteMany({}),
  DisposedStock.deleteMany({}),
  Program.deleteMany({}),
  Department.deleteMany({}),
  Staff.deleteMany({}),
  News.deleteMany({}),
  Gallery.deleteMany({}),
  WebsiteSetting.deleteMany({}),
  Role.deleteMany({}),
  Permission.deleteMany({}),
  AuditLog.deleteMany({}),
  Notification.deleteMany({}),
  Loan.deleteMany({}),
  Report.deleteMany({}),
  SystemSetting.deleteMany({}),
  Equipment.deleteMany({}),
  EquipmentRetirementRequest.deleteMany({}),
  EquipmentArchiveRequest.deleteMany({}),
  Event.deleteMany({}),
  Admission.deleteMany({}),
  ContactMessage.deleteMany({}),
  StockReconciliation.deleteMany({}),
  StockArchiveRequest.deleteMany({}),
]);
await Book.insertMany(SEED_BOOKS.map(({ id: _id, seedImage: img, ...book }) => ({ ...book, coverImage: seedImage(img) })));
const suppliers = await Supplier.insertMany(SEED_SUPPLIERS.map(({ id: _id, ...supplier }) => supplier));
const supplierByName = Object.fromEntries(suppliers.map((supplier) => [supplier.name, supplier._id]));
await StockItem.insertMany(SEED_ITEMS.map(({ id: _id, supplier, ...item }) => ({ ...item, supplierId: supplierByName[supplier] })));
await Department.insertMany(DEPARTMENTS.map(({ id: _id, seedImage: img, ...department }) => ({ ...department, image: seedImage(img) })));
await Program.insertMany(PROGRAMS.map(({ id: _id, seedImage: img, ...program }) => ({ ...program, description: program.description || program.summary, image: seedImage(img) })));
await Staff.insertMany(STAFF.map(({ id: _id, seedImage: img, ...staff }) => ({ ...staff, biography: staff.biography || staff.bio, photo: seedImage(img) })));
await News.insertMany(NEWS.map(({ id: _id, date, seedImage: img, ...news }) => ({ ...news, date, published: true, publishedAt: date, image: seedImage(img) })));
await Gallery.insertMany(GALLERY.map(({ id: _id, seedImage: img, ...gallery }) => ({ ...gallery, title: gallery.title || gallery.caption, caption: gallery.caption, image: seedImage(img) })));
await WebsiteSetting.create({
  key: 'default',
  schoolName: 'Rambura Garçons TVET School',
  logo: seedImage('website/logo.svg'),
  favicon: seedImage('website/logo.svg'),
  siteImages: { 'home.hero': seedImage('website/hero.svg').imageUrl },
  hero: {
    eyebrow: 'Welcome to Rambura Garçons TVET School',
    title: 'Building Skills. Shaping Futures.',
    subtitle: 'Practical technical education that prepares young people for meaningful careers.',
    stats: [
      { value: '500+', label: 'Students' },
      { value: '4', label: 'Programs' },
      { value: '30+', label: 'Staff' },
      { value: '95%', label: 'Success Rate' },
    ],
    studentVoices: { eyebrow: 'Student voices', title: 'Built for confidence beyond the classroom' },
    testimonials: [
      { quote: 'The workshop training gave me confidence to solve real electrical problems from my first day on placement.', name: 'Aline Mukamana', detail: 'Electrical Technology graduate' },
      { quote: 'Rambura Garçons helped me turn an interest in welding into a practical career and a small fabrication business.', name: 'Jean Claude Habimana', detail: 'Welding & Fabrication graduate' },
      { quote: 'The teachers know every learner and push us to build skills we can use beyond the classroom.', name: 'Diane Uwimana', detail: 'Construction student' },
    ],
    progress: { eyebrow: 'Achievements', title: 'Progress you can measure' },
    achievements: [
      { value: '1st', label: 'Nyabihu District Skills Competition', year: '2026' },
      { value: '4', label: 'Industry-focused trade programmes', year: 'Active today' },
      { value: '20+', label: 'Years serving practical education', year: 'Since 2005' },
    ],
    homeContent: {
      heroButtons: { primary: 'Discover More', secondary: 'Learn About Us' },
      highlights: [
        { title: 'Practical', subtitle: 'Training' },
        { title: 'Skilled', subtitle: 'Instructors' },
        { title: 'Modern', subtitle: 'Facilities' },
        { title: 'Career', subtitle: 'Focused' },
      ],
      aboutPreview: {
        eyebrow: 'About Us', title: 'Empowering Youth Through', titleAccent: 'Quality Technical Education',
        description: 'We are committed to providing industry-relevant training, modern facilities and a supportive learning environment that prepares students for successful careers and lifelong impact.',
        imageLabel: 'Hands-on learning', imageTitle: 'Industry-ready practical training',
      },
      programs: { eyebrow: 'Our Programs', title: 'Programs We Offer', button: 'View All Programs', cardAction: 'Learn More' },
      admissionsCta: { eyebrow: 'Admissions open', title: 'Ready to Start Your Journey?', description: 'Join Rambura Garçons TVET School and build the skills for a better future.', button: 'Apply Now' },
    },
  },
  about: {
    heroTitle: 'About Rambura Garçons',
    heroIntro: 'A technical and vocational education and training school formed to serve Nyabihu District and beyond.',
    historyTitle: 'School History',
    history: "Rambura Garçons was founded to answer a clear need in Nyabihu District: skilled tradespeople trained to a professional standard, close to home. Since opening, the school has grown from a single workshop to four full trade departments, graduating classes of electricians, welders, builders, and mechanics who now work across Rwanda's growing construction and industrial sectors.",
    missionTitle: 'Mission',
    mission: 'To equip young Rwandans with practical trade skills, professional discipline, and the confidence to build sustainable livelihoods.',
    visionTitle: 'Vision',
    vision: 'To be the leading TVET institution in Western Province, known for graduates who set the standard in their trades.',
    valuesTitle: 'Core Values',
    values: ['Discipline', 'Craftsmanship', 'Integrity', 'Service to Community'],
    leadershipTitle: 'Leadership',
    leadershipIntro: 'Meet the people guiding Rambura Garçons.',
    facilitiesTitle: 'Facilities',
    facilities: [
      { key: 'electrical', label: 'Electrical wiring workshop' },
      { key: 'welding', label: 'Welding & fabrication bay' },
      { key: 'construction', label: 'Construction training yard' },
      { key: 'automobile', label: 'Automobile mechanics garage' },
      { key: 'library', label: 'School library and reading hall' },
      { key: 'dormitories', label: 'Boarding dormitories' },
    ],
  },
  staffPage: {
    title: 'Our Staff',
    intro: 'The instructors and leaders behind Rambura Garçons.',
  },
  academicsPage: {
    title: 'Academics',
    intro: 'Four trade programs, each built for real workplace readiness.',
  },
  departmentsPage: {
    title: 'Departments',
    intro: 'Four departments, each led by an experienced trade professional.',
  },
  homepageSettings: {
    title: 'Admissions',
    intro: 'Start your journey toward practical skills and a meaningful career.',
    informationTitle: 'Admission Information',
    informationIntro: 'Everything you need to know before applying',
    requirementsTitle: 'Requirements',
    requirementsIntro: 'What you need to qualify for admission',
    requirementsCardTitle: 'Admission Requirements',
    datesTitle: 'Important Dates',
    datesIntro: 'Key dates for the admission cycle',
    datesCardTitle: 'Important Dates',
    processTitle: 'Admission Process',
    processIntro: 'How our admission process works',
    processCardTitle: 'Step-by-Step Process',
    supportTitle: 'Contact & Support',
    supportIntro: "Questions? We're here to help",
    supportCardTitle: 'Get in Touch',
    applicationTitle: 'Admission Application',
    applicationIntro: 'Complete the form below to apply for any of our programs.',
    requirements: [], dates: [], process: '', contactLine: '',
  },
  newsPage: {
    title: 'News',
    intro: 'Updates from around the Rambura Garçons campus.',
  },
  galleryPage: {
    title: 'Gallery',
    intro: 'Life at Rambura Garçons, in and out of the workshop.',
  },
  contactPage: {
    title: 'Contact Us',
    intro: "We'd love to hear from you.",
    informationTitle: 'Get in Touch',
    informationIntro: "We're here to answer any questions you may have",
    developerName: 'Ninziza Aime Gentil, Byiringiro Dady Roger, Niyonsaba Emery',
    developerUrl: '/developers',
  },
  developersPage: {
    title: 'Website Developers',
    intro: 'The people behind the digital experience, content tools, and management system built for Rambura Garçons.',
    teamLabel: 'The team',
    heading: 'Built with purpose.',
    description: "This system brings the school's public story and day-to-day operations into one dependable digital home.",
    developers: [
      { name: 'Ninziza Aime Gentil', role: 'Product & Interface Development' },
      { name: 'Byiringiro Dady Roger', role: 'Platform & Systems Development' },
      { name: 'Niyonsaba Emery', role: 'Data & Experience Development' },
    ],
    capabilities: [
      { label: 'Public website', detail: 'A clear digital front door for students, families, and partners.' },
      { label: 'Content management', detail: 'Tools that keep school information current without code changes.' },
      { label: 'Management system', detail: 'Connected workflows for the people running the school every day.' },
    ],
  },
});
await Equipment.insertMany([
  { assetNumber: 'LAP-001', name: 'ICT Lab Laptop 01', type: 'laptop', brand: 'Dell', model: 'Latitude', serialNumber: 'RG-LAP-001', location: 'ICT Lab', condition: 'good', status: 'available' },
  { assetNumber: 'DES-001', name: 'Administration Desktop', type: 'desktop', brand: 'HP', model: 'ProDesk', serialNumber: 'RG-DES-001', location: 'Administration Office', condition: 'good', status: 'assigned', currentAssignee: { userName: 'Administration Office', assignedAt: new Date() }, assignmentHistory: [{ userName: 'Administration Office', assignedAt: new Date() }] },
]);
await Event.insertMany([
  { title: 'New Academic Year Opening', slug: 'new-academic-year-opening', description: 'Welcome activities and orientation for the new academic year.', startDate: new Date('2026-09-21T08:00:00Z'), location: 'School Assembly Ground', published: true, featured: true },
]);
const permissionKeys = ['users.view', 'users.create', 'users.update', 'users.delete', 'website.view', 'website.create', 'website.update', 'website.delete', 'library.view', 'library.books.create', 'library.books.update', 'library.books.delete', 'library.borrow', 'library.return', 'library.reports', 'stock.view', 'stock.create', 'stock.update', 'stock.in', 'stock.out', 'stock.adjust', 'stock.transfer', 'stock.damage', 'stock.dispose.request', 'stock.dispose.approve', 'stock.archive.request', 'stock.archive.approve', 'stock.reconcile.approve', 'stock.suppliers', 'stock.reports', 'equipment.view', 'equipment.create', 'equipment.update', 'equipment.assign', 'equipment.maintenance', 'equipment.retire.request', 'equipment.retire.approve', 'equipment.archive.request', 'equipment.archive.approve', 'events.view', 'events.manage', 'applications.view', 'applications.update', 'reports.view', 'audit.view', 'settings.view', 'settings.update'];
const permissions = await Permission.insertMany(permissionKeys.map((key) => ({ key, label: key, module: key.split('.')[0] })));
await Role.insertMany([
  { name: 'admin', label: 'IT / System Administrator', permissions: permissions.map((permission) => permission._id) },
  { name: 'librarian', label: 'Librarian', permissions: permissions.filter((permission) => ['library', 'events'].includes(permission.module)).map((permission) => permission._id) },
  { name: 'stock_manager', label: 'Stock Manager', permissions: permissions.filter((p) => ['stock'].includes(p.module) && !['stock.dispose.approve','stock.archive.approve','stock.reconcile.approve'].includes(p.key)).map((p) => p._id) },
  { name: 'equipment_manager', label: 'Equipment Manager', permissions: permissions.filter((p) => ['equipment'].includes(p.module) && !['equipment.retire.approve','equipment.archive.approve'].includes(p.key)).map((p) => p._id) },
  { name: 'management', label: 'School Management / Director', permissions: permissions.filter((permission) => [
    'applications.view', 'applications.update', 'reports.view',
    'library.view', 'library.reports', 'stock.view', 'stock.reports', 'stock.dispose.approve', 'stock.archive.approve', 'stock.reconcile.approve',
    'equipment.view', 'equipment.retire.approve', 'equipment.archive.approve', 'audit.view', 'events.view', 'events.manage',
  ].includes(permission.key)).map((permission) => permission._id) },
]);
// Demo records for EVERY panel (library, stock, equipment, admissions, messages, notifications, logs...).
// Development: on by default. Production: only when SEED_DEMO=true. Turn off anywhere with SEED_DEMO=false.
const withDemo = process.env.SEED_DEMO === 'true' || (process.env.SEED_DEMO !== 'false' && !isProduction);
if (withDemo) console.log(await seedDemoData());

console.log(`Seeded ${users.length} main accounts${withDemo ? ' (+3 extra demo accounts)' : ''}.`);
if (isProduction) {
  console.log('Generated passwords (shown only once - save them now, then change them after the first login):');
  for (const [, username, , password] of users) console.log(`  ${username}: ${password}`);
} else {
  console.log('Development demo logins: admin / Admin@123, librarian / Library@123, stock / Stock@123, equipment / Equipment@123, director / Director@123');
  if (withDemo) console.log('Extra demo accounts (password Demo@12345): librarian2, registrar (management), stock2 (inactive)');
}
process.exit(0);
